[package]
name = "haze"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = ["engine", "libchess", "libengine", "tournament"]

[[bin]]
name = "haze"
path = "engine/src/main.rs"

[dependencies]
libengine = { path = "libengine" }
